# Generated by Django 3.2.4 on 2021-10-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterestMsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=500)),
                ('read', models.BooleanField(default=False, verbose_name='Read')),
                ('replied', models.BooleanField(default=False, verbose_name='Replied')),
            ],
            options={
                'verbose_name': 'InterestMsg',
                'verbose_name_plural': 'InterestMsg',
                'managed': True,
            },
        ),
    ]
